version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bot
      - MYSQL_USER=application
      - MYSQL_PASSWORD=application
    ports:
      - "3306:3306"
    volumes:
      - ./data/db:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data: