version: "3.8"

services:
  studybot:
    build: .
    container_name: studybot-app
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - DB_NAME=${DB_NAME:-bot}
      - DB_USERNAME=${DB_USERNAME:-application}
      - DB_PASSWORD=${DB_PASSWORD:-application}
      - VOICE_CHANNEL_NAME=${VOICE_CHANNEL_NAME:-study}
      - TEXT_CHANNEL_NAME=${TEXT_CHANNEL_NAME:-study-time}
    restart: unless-stopped
    volumes:
      - ./logs/app:/app/logs
    networks:
      - studybot-network

networks:
  studybot-network:
    external: true