spring:
  application:
    name: studybot
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: false
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
discord:
  bot:
    token:
voice-channel:
  target-channel-name: study
text-channel:
  target-channel-name: study-time
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:studybot;MODE=MySQL
    username: sa
    password:
---
spring:
  config:
    activate:
      on-profile: proc
  datasource:
    url: jdbc:mysql://localhost:3306/bot
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: application
    password: application
    hikari:
      maximum-pool-size: 5
      minimum-idle: 10
      max-lifetime: 1800000
      connection-timeout: 10000
      idle-timeout: 600000
  jpa:
    hibernate:
      ddl-auto: none
  devtools:
    add-properties: false
